apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials-secret
  namespace: shop
type: Opaque
data:
  admin-user: YWRtaW4=
  admin-password: cGFzc3dvcmQxMjM=
  userKey: YWRtaW4=
  passwordKey: cGFzc3dvcmQxMjM=