apiVersion: v1
kind: Secret
metadata:
  name: inventory-postgres-secrets
  namespace: shop
type: Opaque
data:
  POSTGRES_DB: aW52ZW50b3J5 #inventory
  POSTGRES_USER: aW52ZW50b3J5 #inventory
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM= #password123
