apiVersion: v1
kind: Secret
metadata:
  name: order-postgres-secret
  namespace: shop
type: Opaque
data:
  POSTGRES_DB: b3JkZXJz #orders
  POSTGRES_USER: b3JkZXJz #orders
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM= #password123
